version: "3"
services:
  app:
    image: spring/library:latest
    container_name: 'library'
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    ports:
      - '8080:8080'

  prometheus:
    image: prom/prometheus:v2.4.3
    container_name: 'prometheus'
    volumes:
      - ./monitoring/prometheus:/etc/prometheus/
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:5.2.4
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config.monitoring
    depends_on:
      - prometheus
